<?php

$queryProfessor = $conexao->prepare("  
SELECT 
	
	 PPESSOA.NOME			AS PROFESSOR
	,SPROFESSOR.CHAPA		AS CHAPA
	,SCUR.NOME				AS CURSO
	,STURMADISC.CODTURMA	AS TURMA
	,STURMADISC.CODDISC		AS CODIGO_DISCIPLINA
	,SDISCIPLINA.NOME		AS DISCIPLINA
	
	
FROM
	SPROFESSOR					(NOLOCK)
	JOIN SPROFESSORTURMA		(NOLOCK) ON SPROFESSORTURMA.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
								AND SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF
	JOIN SHORARIOPROFESSOR		(NOLOCK) ON SHORARIOPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
								AND SHORARIOPROFESSOR.IDPROFESSORTURMA = SPROFESSORTURMA.IDPROFESSORTURMA
	JOIN SHORARIOTURMA			(NOLOCK) ON SHORARIOTURMA.CODCOLIGADA = SHORARIOPROFESSOR.CODCOLIGADA
								AND SHORARIOTURMA.IDHORARIOTURMA = SHORARIOPROFESSOR.IDHORARIOTURMA
	JOIN STURMADISC				(NOLOCK) ON STURMADISC.CODCOLIGADA = SHORARIOTURMA.CODCOLIGADA
								AND STURMADISC.IDTURMADISC = SHORARIOTURMA.IDTURMADISC
	JOIN SHORARIO				(NOLOCK) ON SHORARIOTURMA.CODCOLIGADA = SHORARIO.CODCOLIGADA 
								AND SHORARIOTURMA.CODHOR = SHORARIO.CODHOR
	JOIN SDISCIPLINA			(NOLOCK) ON SDISCIPLINA.CODCOLIGADA	= STURMADISC.CODCOLIGADA
								AND SDISCIPLINA.CODDISC	= STURMADISC.CODDISC
	JOIN SPLETIVO				(NOLOCK) ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
								AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
								AND SPLETIVO.CODTIPOCURSO = 7
	LEFT JOIN STURMA				(NOLOCK) ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
									AND STURMA.CODTURMA = STURMADISC.CODTURMA
	LEFT JOIN SHABILITACAOFILIAL SHAB	(NOLOCK) ON SHAB.CODCOLIGADA = STURMA.CODCOLIGADA
										AND SHAB.IDHABILITACAOFILIAL = STURMA.IDHABILITACAOFILIAL
	LEFT JOIN SCURSO SCUR				(NOLOCK) ON SCUR.CODCOLIGADA = SHAB.CODCOLIGADA
										AND SCUR.CODCURSO = SHAB.CODCURSO
	LEFT JOIN SCAMPUS SCAM		(NOLOCK) ON SCAM.CODCAMPUS = STURMADISC.CODCAMPUS
	JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
	JOIN PFUNC(NOLOCK) ON PFUNC.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
								AND PFUNC.CHAPA = SPROFESSOR.CHAPA	
	JOIN PFUNCAO(NOLOCK) ON PFUNC.CODFUNCAO = PFUNCAO.CODIGO
								AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA
	JOIN SPROFESSORMEC			(NOLOCK) ON SPROFESSORMEC.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
								AND SPROFESSORMEC.CODPROF = SPROFESSOR.CODPROF
	/*JOIN PFCOMPL				(NOLOCK) ON PFCOMPL.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
											AND PFCOMPL.CHAPA = SPROFESSOR.CHAPA*/
WHERE
SPLETIVO.CODCOLIGADA = 1
AND STURMADISC.CODTURMA = '$codTurma'
AND STURMADISC.CODDISC = '$codDisciplina'
AND SCAM.CODCAMPUS = '$codCampus'
GROUP BY
	SCAM.DESCRICAO
	,PPESSOA.NOME
	,SPROFESSOR.CHAPA
	,SCUR.NOME
	,STURMADISC.CODTURMA
	,STURMADISC.CODDISC
	,SDISCIPLINA.NOME
	,SHORARIO.DIASEMANA
	,SHORARIO.DIASEMANA
	,SPROFESSOR.CODTITULACAO
	,PFUNCAO.NOME
	,SPROFESSORMEC.REGIMETRABALHO
ORDER BY 1
");
?>