<?php

$queryDisc = $conexao->prepare(" 
SELECT DISTINCT 
    STURMADISC.IDTURMADISC              AS CODIGO,
    SHABILITACAOFILIAL.IDHABILITACAOFILIAL		AS IDHABOFFICIAL,
    SMATRICULA.IDTURMADISC              AS IDTURMADISC,
    SCURSO.CODCURSO                     AS COD_CURSO,
    STURMADISC.CODTURMA                 AS COD_TURMA,
    STURMADISC.CODDISC                  AS COD_DISCIPLINA,
    SALUNO.RA                           AS RA,
    SDISCIPLINA.NOME                    AS DISCIPLINA
FROM 
    SALUNO
        JOIN PPESSOA                    ON PPESSOA.CODIGO =      SALUNO.CODPESSOA
        JOIN SHABILITACAOALUNO          ON SHABILITACAOALUNO.RA = SALUNO.RA
                           AND SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
        JOIN SHABILITACAOFILIAL    WITH(NOLOCK)  ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL   = SHABILITACAOALUNO.IDHABILITACAOFILIAL
                           AND SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
        JOIN SCURSO                WITH(NOLOCK) ON SCURSO.CODCURSO  = SHABILITACAOFILIAL.CODCURSO
                           AND SCURSO.CODTIPOCURSO = 7
        JOIN SHABILITACAO          WITH(NOLOCK)  ON SHABILITACAO.CODCOLIGADA = SALUNO.CODCOLIGADA
                            AND SHABILITACAO.CODCURSO = SCURSO.CODCURSO
                            AND SHABILITACAO.CODHABILITACAO  = SHABILITACAOFILIAL.CODHABILITACAO
        JOIN SMATRICULA             (NOLOCK) ON SMATRICULA.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                            AND SMATRICULA.RA = SHABILITACAOALUNO.RA
                            AND SMATRICULA.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        JOIN SPLETIVO               (NOLOCK) ON SPLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
                            AND SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
                            AND SPLETIVO.CODTIPOCURSO = SALUNO.CODTIPOCURSO
        JOIN STURNO             (NOLOCK) ON STURNO.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA

                            AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
                            AND STURNO.CODTIPOCURSO = 7
        JOIN STURMADISC         (NOLOCK) ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA

                            AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
                            AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET
                            AND STURMADISC.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL

        JOIN   SDISCIPLINA      (NOLOCK)     ON       SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                            AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC

WHERE 
        SALUNO.CODCOLIGADA = 1
        AND	SHABILITACAOALUNO.CODSTATUS NOT IN (83,84)
        AND SALUNO.RA = '$ra'
        $filtroTratado
        ");


$queryDisc->execute();
$resultadoDisc = $queryDisc->fetchAll(PDO::FETCH_ASSOC);

?>