<?php

try {
    // Preparando a query
    $queryA = $conexao->prepare(" 
    SELECT DISTINCT
    SHABILITACAOALUNO.CODCAMPUS    AS CAMPUS,
    PPESSOA.NOME					AS NOME,
    SALUNO.RA                       AS RA,
    scurso.nome						AS CURSO,
    scurso.CODCURSO                 AS CODCURSO,
    PPESSOA.EMAIL					AS Email,
    STURNO.NOME						AS TURNO,
    SHABILITACAOFILIAL.CODGRADE    AS GRADE,
    SHABILITACAOFILIAL.IDHABILITACAOFILIAL AS MATRIZ,
    SPLETIVO.CODPERLET			AS PERIODOLETIVO,
    SHABILITACAOFILIAL.CODFILIAL AS CODFILIAL

    
    

FROM SALUNO

/* FAZ A RELAÇÃO DA TABELA SALUNO COM A TABELA PPESSO ONDE HÁ VÁRIOS CAMPOS DE DADOS CADASTRAIS*/
JOIN	PPESSOA								ON	PPESSOA.CODIGO = SALUNO.CODPESSOA

/* FAZ A RELAÇÃO DA TABELA SALUNO COM A TABELA SCONTRATO PARA CHECAR SE O ALUNO POSSUI UM CONTRATO VIGENTE */
LEFT JOIN	SCONTRATO	(NOLOCK)			ON	SCONTRATO.CODCOLIGADA	= SALUNO.CODCOLIGADA
                                        AND	SCONTRATO.RA			= SALUNO.RA

/* FAZ A RELAÇÃO DA TABELA SCONTRATO COM A TABELA SPLETIVO PARA VALIDAR O PERÍODO LETIVO ATUAL E TAMBÉM VALIDA O TIO DE CURSO (GRAD., PÓS, EXT, COLEGIO)*/
JOIN	SPLETIVO	(NOLOCK)				ON	SPLETIVO.CODCOLIGADA	= SCONTRATO.CODCOLIGADA
                                        AND	SPLETIVO.IDPERLET		= SCONTRATO.IDPERLET
                                        AND SPLETIVO.CODTIPOCURSO = 7

/* aqui faz a validação da estrutura curricula atual do aluno com a filial que estuda (realengo ou penha) */
JOIN	SHABILITACAOFILIAL	(NOLOCK)		ON	SHABILITACAOFILIAL.CODCOLIGADA				= SCONTRATO.CODCOLIGADA
                                        AND	SHABILITACAOFILIAL.IDHABILITACAOFILIAL		= SCONTRATO.IDHABILITACAOFILIAL

/* aqui faz a validação da matriz aplicada para a definição do turno de oferta (manhã, tarde, noite, integral)*/
JOIN	SHABILITACAO	(NOLOCK)			ON	SHABILITACAO.CODCOLIGADA		= SHABILITACAOFILIAL.CODCOLIGADA
                                        AND	SHABILITACAO.CODCURSO			= SHABILITACAOFILIAL.CODCURSO
                                        AND	SHABILITACAO.CODHABILITACAO		= SHABILITACAOFILIAL.CODHABILITACAO

/* aqui faz a validação estrutura curricular atual do aluno */
JOIN	SHABILITACAOALUNO	(NOLOCK)		ON	SHABILITACAOALUNO.CODCOLIGADA				= SHABILITACAOFILIAL.CODCOLIGADA
                                        AND	SHABILITACAOALUNO.IDHABILITACAOFILIAL		= SHABILITACAOFILIAL.IDHABILITACAOFILIAL
                                        AND	SHABILITACAOALUNO.RA						= SALUNO.RA

/* aqui faz a validação do curso  com a filial (realengo ou penha)*/
JOIN	SCURSO	(NOLOCK)					ON	SCURSO.CODCOLIGADA			= SHABILITACAOFILIAL.CODCOLIGADA
                                        AND	SCURSO.CODCURSO				= SHABILITACAOFILIAL.CODCURSO

/* aqui faz a validação do turno (pegar o nome do turno)da estrutura curricular do aluno */
JOIN	STURNO	(NOLOCK)					ON	STURNO.CODCOLIGADA			= SHABILITACAOFILIAL.CODCOLIGADA
                                        AND	STURNO.CODTURNO				= SHABILITACAOFILIAL.CODTURNO

/* aqui faz a validação da unidade com base na da estrutura curricular atual do aluno */
LEFT JOIN	SHABILITACAOFILIALCAMPUS	(NOLOCK)	ON	SHABILITACAOFILIALCAMPUS.CODCOLIGADA			= SHABILITACAOALUNO.CODCOLIGADA
                                                AND	SHABILITACAOFILIALCAMPUS.IDHABILITACAOFILIAL	= SHABILITACAOALUNO.IDHABILITACAOFILIAL
                                                AND	SHABILITACAOFILIALCAMPUS.CODCAMPUS				= SHABILITACAOALUNO.CODCAMPUS

LEFT JOIN	SDISCGRADE	(NOLOCK)	ON	SHABILITACAOFILIAL.CODCOLIGADA			= SDISCGRADE.CODCOLIGADA
                                AND  SHABILITACAOFILIAL.CODCURSO = SDISCGRADE.CODCURSO
                                AND  SHABILITACAOFILIAL.CODHABILITACAO = SDISCGRADE.CODHABILITACAO
                                AND SHABILITACAOFILIAL.CODGRADE = SDISCGRADE.CODGRADE

LEFT JOIN	SDISCIPLINA	(NOLOCK)	ON	SDISCIPLINA.CODDISC			= SDISCGRADE.CODDISC
                                

/* aqui faz a validação da unidade (pegar o nome da unidade) com base na unidade em que o aluno está matriculado (Penha ou Realengo) */
LEFT JOIN	SCAMPUS		(NOLOCK)	ON	SCAMPUS.CODCAMPUS			= SHABILITACAOFILIALCAMPUS.CODCAMPUS

/* aqui faz a validação do tipo de ingresso do aluno (pegar o nome do tipo de ingresso) com base no tipo de ingreso assumido pelo aluno (portador, transferência....) */
LEFT JOIN STIPOINGRESSO (NOLOCK)	ON	STIPOINGRESSO.CODCOLIGADA		= SHABILITACAOALUNO.CODCOLIGADA
                                AND	STIPOINGRESSO.CODTIPOINGRESSO	= SHABILITACAOALUNO.CODTIPOINGRESSO

/* aqui faz a validação tabela spessoa com ppssoa para que possa buscar a Especialização da Pessoa */
LEFT JOIN SPESSOA (NOLOCK)			ON	SPESSOA.CODIGO = PPESSOA.CODIGO

/* aqui faz a validação tabela sinstituicao com spssoa para que possa buscar o nome da IES de segundo grau do aluno */
LEFT JOIN SINSTITUICAO (NOLOCK)		ON	SINSTITUICAO.CODINST = SPESSOA.CODINST2GRAU

/* aqui faz a validação tabela sstatus com shabilitacaoaluno para buscar o nome referente a situação de matricula do aluno */
JOIN	SSTATUS		(NOLOCK)		ON	SSTATUS.CODCOLIGADA	= SHABILITACAOALUNO.CODCOLIGADA
                                AND	SSTATUS.CODSTATUS		= SHABILITACAOALUNO.CODSTATUS
                                AND SSTATUS.CODTIPOCURSO = 7

LEFT JOIN (
SELECT	SMATRICPL.CODCOLIGADA
    , SMATRICPL.RA
    , SMATRICPL.IDPERLET
    , SMATRICPL.IDHABILITACAOFILIAL
    , SSTATUS.DESCRICAO	
    , SMATRICPL.DTMATRICULA	
    , DATAMATRICULA.[DATA MATRÍCULA]
FROM SMATRICPL
JOIN	SSTATUS		(NOLOCK)		ON	SSTATUS.CODCOLIGADA	= SMATRICPL.CODCOLIGADA
                                AND	SSTATUS.CODSTATUS	= SMATRICPL.CODSTATUS
LEFT JOIN (
SELECT	SMATRICPL.CODCOLIGADA
    , SMATRICPL.RA
    , SMATRICPL.IDHABILITACAOFILIAL
    , MIN(SMATRICPL.DTMATRICULA)	AS [DATA MATRÍCULA]
FROM SMATRICPL
WHERE	SMATRICPL.CODCOLIGADA  = 1
 AND SMATRICPL.CODSTATUS			IN (SELECT SSTATUS2.CODSTATUS FROM SSTATUS SSTATUS2 (NOLOCK)  WHERE SSTATUS2.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SSTATUS2.PLATIVO = 'S') 
GROUP BY	SMATRICPL.CODCOLIGADA
        , SMATRICPL.RA
        , SMATRICPL.IDHABILITACAOFILIAL
) AS DATAMATRICULA
ON	DATAMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
AND	DATAMATRICULA.RA = SMATRICPL.RA
AND DATAMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
WHERE	SMATRICPL.CODCOLIGADA  = 1
 AND SMATRICPL.CODSTATUS			IN (SELECT SSTATUS2.CODSTATUS FROM SSTATUS SSTATUS2 (NOLOCK)  WHERE SSTATUS2.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SSTATUS2.PLATIVO = 'S') 
) AS MATRICPL 
ON	MATRICPL.CODCOLIGADA			= SCONTRATO.CODCOLIGADA
AND	MATRICPL.RA						= SCONTRATO.RA
AND	MATRICPL.IDPERLET				= SCONTRATO.IDPERLET
AND	MATRICPL.IDHABILITACAOFILIAL	= SCONTRATO.IDHABILITACAOFILIAL

/* aqui faz a checagem do cenário financeiro do aluno com base nas suas parcelas, lançamentos e as baixa do boleto de matrícula atraves do codigo 78 */
LEFT JOIN (
SELECT	  SPARCELA.CODCOLIGADA
    , SPARCELA.CODCONTRATO
    , SPARCELA.IDPERLET
    , SPARCELA.RA
    , CASE FLAN.STATUSLAN
        WHEN 0 THEN 'EM ABERTO'
        WHEN 1 THEN 'PAGO'
        WHEN 3 THEN 'PAGO POR ACORDO'
        WHEN 4 THEN 'PAGO PARCIALMENTE'
        WHEN 9 THEN 'CANCELADO'
        ELSE 'NÃO GERADO'
    END AS STATUS
    , FLAN.DATABAIXA
FROM SPARCELA

LEFT JOIN SLAN (NOLOCK)					ON	SLAN.CODCOLIGADA	= SPARCELA.CODCOLIGADA
                                    AND	SLAN.IDPARCELA		= SPARCELA.IDPARCELA
LEFT JOIN FLAN (NOLOCK)					ON	FLAN.CODCOLIGADA	= SLAN.CODCOLIGADA
                                    AND	FLAN.IDLAN			= SLAN.IDLAN
WHERE	SPARCELA.CODCOLIGADA = 1
AND	SPARCELA.PARCELA = 1
AND	SPARCELA.CODSERVICO = 4
AND	FLAN.STATUSLAN IN (1, 3, 4)
AND FLAN.CODCFO NOT IN (SELECT CODCFO  FROM SBOLSA WHERE SBOLSA.CODCOLIGADA = 1 AND SBOLSA.CODCFO IS NOT NULL)
) AS PARCELA 
ON	PARCELA.CODCOLIGADA	= SCONTRATO.CODCOLIGADA
AND	PARCELA.RA			= SCONTRATO.RA
AND	PARCELA.IDPERLET	= SCONTRATO.IDPERLET
AND	PARCELA.CODCONTRATO	= SCONTRATO.CODCONTRATO
LEFT JOIN (
SELECT	SMATRICULA.CODCOLIGADA
    , SMATRICULA.RA
    , SMATRICULA.IDPERLET
    , SMATRICULA.IDHABILITACAOFILIAL
    /* , SSTATUS.DESCRICAO */
    , COUNT(SMATRICULA.IDTURMADISC) AS DISCIPLINAS
    , SUM(SMATRICULA.NUMCREDITOSCOB) AS CREDITOS 
FROM SMATRICULA
LEFT JOIN SCONTRATO	ON	SCONTRATO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
                AND	SCONTRATO.RA = SMATRICULA.RA
                AND	SCONTRATO.IDPERLET = SMATRICULA.IDPERLET
                AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
JOIN	SSTATUS		(NOLOCK)		ON	SSTATUS.CODCOLIGADA	= SMATRICULA.CODCOLIGADA
                                AND	SSTATUS.CODSTATUS	= SMATRICULA.CODSTATUS
WHERE	SMATRICULA.CODCOLIGADA  = 1
and		SMATRICULA.CODSTATUS IN (SELECT SSTATUS2.CODSTATUS FROM SSTATUS SSTATUS2 (NOLOCK)  WHERE SSTATUS2.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND SSTATUS2.DIINCALUNODISC = 'S')
GROUP BY	SMATRICULA.CODCOLIGADA 
        , SMATRICULA.RA
        , SMATRICULA.IDPERLET
        , SMATRICULA.IDHABILITACAOFILIAL
        /* , SSTATUS.DESCRICAO*/
HAVING SUM(SMATRICULA.NUMCREDITOSCOB) > 0
) AS DISCIPLINA 
ON	DISCIPLINA.CODCOLIGADA	= SCONTRATO.CODCOLIGADA
AND	DISCIPLINA.RA			= SCONTRATO.RA
AND	DISCIPLINA.IDPERLET		= SCONTRATO.IDPERLET
AND	DISCIPLINA.IDHABILITACAOFILIAL	= SCONTRATO.IDHABILITACAOFILIAL
LEFT JOIN (
SELECT	SLOGPLETIVO.CODCOLIGADA
    , SLOGPLETIVO.IDPERLET
    , SLOGPLETIVO.IDHABILITACAOFILIAL
    , SLOGPLETIVO.RA
    , GUSUARIO.CODUSUARIO
    , GUSUARIO.NOME
    /*,  CONVERT(VARCHAR, BASE.[DATA DE ALTERAÇÃO], 101) + ' ' + CONVERT(VARCHAR, BASE.[DATA DE ALTERAÇÃO], 108) AS [DATA ALTERAÇÃO] */
    , BASE.[DATA DE ALTERAÇÃO] AS [DATA ALTERAÇÃO]
FROM	SLOGPLETIVO

JOIN GUSUARIO ON GUSUARIO.CODUSUARIO = SLOGPLETIVO.USUARIO
JOIN (
SELECT	  SLOGPLETIVO.CODCOLIGADA
    , SLOGPLETIVO.IDPERLET
    , SLOGPLETIVO.IDHABILITACAOFILIAL
    , SLOGPLETIVO.RA
    , MAX(SLOGPLETIVO.DTALTERACAO)	AS [DATA DE ALTERAÇÃO]
FROM	SLOGPLETIVO

WHERE	SLOGPLETIVO.CODCOLIGADA = 1


GROUP BY SLOGPLETIVO.CODCOLIGADA
    , SLOGPLETIVO.IDPERLET
    , SLOGPLETIVO.IDHABILITACAOFILIAL
    , SLOGPLETIVO.RA
) AS BASE
ON	BASE.CODCOLIGADA = SLOGPLETIVO.CODCOLIGADA
AND	BASE.IDPERLET = SLOGPLETIVO.IDPERLET
AND	BASE.IDHABILITACAOFILIAL = SLOGPLETIVO.IDHABILITACAOFILIAL
AND BASE.RA = SLOGPLETIVO.RA
AND BASE.[DATA DE ALTERAÇÃO] = SLOGPLETIVO.DTALTERACAO
) AS LOG2
ON	LOG2.CODCOLIGADA = SCONTRATO.CODCOLIGADA
AND	LOG2.IDPERLET = SCONTRATO.IDPERLET
AND	LOG2.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
AND LOG2.RA = SCONTRATO.RA
LEFT JOIN (
        SELECT 
        SFAIXACRED.IDPERLET
        ,SFAIXACRED.IDHABILITACAOFILIAL
        ,SFAIXACRED.VALCRED VALOR 
        FROM SFAIXACRED (NOLOCK)
        WHERE
        SFAIXACRED.CODCOLIGADA = 1
) FAIXACREDITO
ON FAIXACREDITO.IDPERLET = SPLETIVO.IDPERLET
AND FAIXACREDITO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE 

    SALUNO.CODCOLIGADA = 1
    AND SALUNO.RA  = '$ra'
    AND	SHABILITACAOALUNO.CODSTATUS NOT IN (83,84)
    $filtro
   
    ");

    // Executando a consulta
    $queryA->execute();

    // Fetching data
    $result = $queryA->fetchAll(PDO::FETCH_ASSOC);

    

} catch (Exception $e) {
    // Tratamento de erro
    echo "Erro: " . $e->getMessage();
}
?>
